/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DraggableContainer {
        "containerTitle": string;
        "group": string;
    }
    interface DraggableItem {
        "assigneeAvatar": string;
        "dueDate": string;
        "taskTitle": string;
    }
}
declare global {
    interface HTMLDraggableContainerElement extends Components.DraggableContainer, HTMLStencilElement {
    }
    var HTMLDraggableContainerElement: {
        prototype: HTMLDraggableContainerElement;
        new (): HTMLDraggableContainerElement;
    };
    interface HTMLDraggableItemElement extends Components.DraggableItem, HTMLStencilElement {
    }
    var HTMLDraggableItemElement: {
        prototype: HTMLDraggableItemElement;
        new (): HTMLDraggableItemElement;
    };
    interface HTMLElementTagNameMap {
        "draggable-container": HTMLDraggableContainerElement;
        "draggable-item": HTMLDraggableItemElement;
    }
}
declare namespace LocalJSX {
    interface DraggableContainer {
        "containerTitle"?: string;
        "group"?: string;
    }
    interface DraggableItem {
        "assigneeAvatar"?: string;
        "dueDate"?: string;
        "taskTitle"?: string;
    }
    interface IntrinsicElements {
        "draggable-container": DraggableContainer;
        "draggable-item": DraggableItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "draggable-container": LocalJSX.DraggableContainer & JSXBase.HTMLAttributes<HTMLDraggableContainerElement>;
            "draggable-item": LocalJSX.DraggableItem & JSXBase.HTMLAttributes<HTMLDraggableItemElement>;
        }
    }
}
